INSERT INTO CONTACT(ID, EMAIL, NAME) VALUES(1, 'ADMIN@SUPERCHAT.COM', 'ADMIN');
INSERT INTO CONTACT(ID, EMAIL, NAME) VALUES(2, 'OWNER@SUPERCHAT.COM', 'OWNER');
INSERT INTO MESSAGE_TEMPLATE(ID, EDITOR_ID, TEMPLATE, PARAMETERS) VALUES ( 1, 1, 'HELLO {{firstName}}, The current Bitcoin price is {{bitcoinPrice}}', 'firstName,bitcoinPrice')